[book]
authors = ["Philipp Joram"]
language = "en"
multilingual = false
src = "src"
title = "Philipp Joram's Place"

[output.html]
additional-css = [
  "theme/external-links.css",
]

[output.html.print]
enable = false

[output.html.fold]
enable = true
level = 0

[output.linkcheck]
optional = true
warning-policy = "error"
