name: Deploy mdBook site to Pages

on:
  push:
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Default to bash
defaults:
  run:
    shell: bash

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Check out repository"
        uses: actions/checkout@v4
      - name: "Install Nix"
        uses: DeterminateSystems/nix-installer-action@v9
      - name: "Set up Nix cache"
        uses: DeterminateSystems/magic-nix-cache-action@v3
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v4
      - name: Build with mdBook
        run: |
          nix build '.#book'
      # XXX: https://github.com/actions/deploy-pages/issues/58
      - name: "Fix permissions on build output"
        run: |
          cp --recursive --dereference --no-preserve=mode,ownership result public
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public/html

  # Deployment job
  deploy:
    # Allow one concurrent deployment
    concurrency:
      group: "deployment"
      cancel-in-progress: true
    name: "Deploy rendered book to Pages"
    if: success() && github.ref == 'refs/heads/main'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
